#!/bin/bash

which stow > /dev/null 2>&1 || { echo "Error: Could not locate GNU Stow"; exit 1; }

operation=${1--R}

case "${operation}" in
    -h|--help)
        echo "Usage: install [OPTION]"
        echo
        echo "  -D  Unstow packages"
        echo "  -R  Restow packages (default)"
        echo "  -S  Stow packages"
        exit 0
        ;;
    -D|-S|-R)
        ;;
    *)
        echo "Error: Unsupported operation ${operation}"
        exit 1
        ;;
esac

function stow_all {
    while read -r package; do
        stow_one "$(basename "${package}")" "$1"
    done < <(find "$1" -mindepth 1 -maxdepth 1 -type d)
}

function stow_one {
    echo "|> Stowing $1"
    eval stow -v -d "$2" -t ~ ${operation} "$1"
}

# Multiple packages will link into ~/.local/bin so we have to make sure it exists or
# else the first one will occupy it and all others will fail
[[ ! -d "~/.local/bin" ]] && mkdir -pv ~/.local/bin

root=$(cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" > /dev/null 2>&1 \
    && git rev-parse --show-toplevel)

stow_all "${root}/stow/common"

case "$(uname -s)" in
    Linux*)
        stow_all "${root}/stow/linux"
        ;;
    Darwin*)
        stow_all "${root}/stow/mac"
        ;;
    *)
        echo "Error: Unknown system $(uname -s)"
        ;;
esac
