#!/bin/bash

which stow > /dev/null 2>&1 || { echo "Error: Could not locate GNU Stow binary"; exit 1; }

function stow_all {
    while read -r package; do
        stow_one "$(basename "${package}")" "$1"
    done < <(find "$1" -mindepth 1 -maxdepth 1 -type d)
}

function stow_one {
    stow -v -d "$2" -t ~ -R "$(basename "$1")"
}

root=$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)
stow_all "${root}/common"
[[ -d "$1" ]] && stow_all "$1"
